# Uncomment the next line to define a global platform for your project
#
# platform :ios, '9.0'

target 'Catstagram' do
  #use_frameworks!

  pod 'AFNetworking'
  pod 'Texture'

  pod 'Yoga', '~> 1.3'
  pod 'Firebase', '~> 3.15'
  #pod 'FirebaseUI', '~> 3.1'
end
