//
//  Friend+CoreDataClass.swift
//  PetPal
//
//  Created by dengjiangzhou on 2018/9/17.
//  Copyright © 2018年 Razeware. All rights reserved.
//
//

import Foundation
import CoreData


public class Friend: NSManagedObject {
    
    
    var age : Int {
        if let dob = dob {
            return Calendar.current.dateComponents([.year], from: dob , to: Date()).year!
        }
        else{
            return 0
        }
    }
    
    

}


// The only time, Core Data will recreate this class here,

// is if we delete it

//  不删除，就不会重新创建




































































// 隔壁的


// 记得， do not want to add any custom code,
//  in this extension here.

// this is what is generated by core data.








// @NSManaged public var photo: NSData?
//  我擦， 不是 Data



// @NSManaged public var dob: Date?
// 手动替换

